import{S as f,i as d}from"./assets/vendor-9310f15c.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();document.querySelector(".gallery");const l=document.querySelector(".search-form"),m=document.querySelector(".loader"),p=document.querySelector(".gallery"),y="https://pixabay.com/api/",h="41928121-1cda58f07b164a8f6335ccf06",g=document.querySelector(".search-btn");l.addEventListener("submit",s=>{s.preventDefault();const t=l.query.value.trim();if(!t){i("The search field can't be empty! Please, enter your request!");return}const n=`${y}?key=${h}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true`;b(n).then(o=>{o.hits.length===0&&(i("Sorry, there are no images matching your search query. Please, try again!"),c(!1)),p.innerHTML=q(o.hits),c(!1),new f(".gallery-item a",{captionsData:"alt",captionDelay:250}),l.reset()}).catch(o=>console.error(o))});function b(s){return c(!0),fetch(s).then(t=>{if(!t.ok)throw new Error(t.ststusText);return t.json()})}function q(s){return s.map(({webformatURL:t,largeImageURL:n,tags:o,likes:e,views:r,comments:a,downloads:u})=>`
        <li class="gallery-item">
  <a class="gallery-link" href="${n}">
    <img
      class="gallery-image"
      src="${t}"
      alt="${o}"
    />
    <p class="gallery-descr">Likes: <span class="descr-span">${e}</span> Views: <span class="descr-span">${r}</span> Comments: <span class="descr-span">${a}</span> Downloads: <span class="descr-span">${u}</span></p>
  </a>
</li>`).join("")}function i(s){d.show({class:"error-svg",position:"topRight",icon:"error-svg",message:s,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function c(s=!0){m.style.display=s?"inline-block":"none",g.disabled=s}
//# sourceMappingURL=commonHelpers.js.map
